### ISSUE TITLE
메인 페이지 최소 구색 갖추기

### ISSUE THREAD

**Issue by singleview-co-kr** [mookhouse/xe-component#11]
- 닥터앙쥬 전문가 Q&A -> /baby_grow_health 최소 7개 포스팅
- 브랜드 스토리 -> /brand_story 최소 4개 포스팅
- 배너 4개 등록

**Comment by ainhye** [comment]
닥터앙쥬 전문가 Q&A -> /baby_grow_health  : 월령별 아기 발달 1개월 ~ 8개월 까지 등록완료
브랜드 스토리 -> /brand_story  : 모바일 최소수량 맞춰서 8개 등록완료

**Comment by singleview-co-kr** [comment]
PC MOB 각각 배너 이미지 업로드하여 완성도 확보

**Comment by ainhye** [comment]
PC MOB 각각 배너 이미지 2개씩 업로드완료
