### ISSUE TITLE
산후 조리원 포스팅 3건

### ISSUE THREAD

**Issue by singleview-co-kr** [mookhouse/xe-component#19]
조리원 소개 동영상은 내년 이후에 재검토

- 조리원 원장은 오픈 직후의 조리원 가장 좋은 모습을 동영상으로 보여주고 싶다.
- 그런데 오픈 직후의 상태는 현재 촬영할 수 없고, 조리원이 제공한 자료를 편집하는 것이 최선이다
- 소비자는 조리원의 가장 좋은 모습이 아니고 조리원의 현재 모습을 보고 싶다.
- 소비자는 절대로 조리원을 방문해서 살펴보고 계약한다. 홈페이지에서 자료만 보고 결정하지 않는다.

**Comment by ainhye** [comment]
산모 입장에서, 
어차피 조리원에 방문해보고 결정하지만 그럼에도 불구하고 컨텐츠에서 보고 싶은 정보는

1) 1 주일치 식사+간식 사진

2) 사용 중인 시설 사진 
웹사이트만 보면 모두 호텔 같음. 현실성이 없기 때문

3) 가격 
웹사이트마다 돌아다니면서 가격 비교하는 것이 매우 번거로움. 
oo구 몇 곳 비교하면서 가격이 같이 나와있으면 본인 버짓으로 선택 가능한 곳을 
바로 추릴 수 있어서 좋을 것 같다고 함

4) 마사지 가격 
1) 공개되어 있지 않기 때문에 방문 상담 시 네고된다고 생각하지만 
막상 방문하면 가격테이블을 제시하며 별도로 할인이 있지는 않았다고 함
2) 왜 공개 안 하는지, 카페나 후기에서 물어봐도 쪽지로만 은밀하게 오가는지 모르겠다고 함.
> 마사지 가격을 전화로 물어보는 것을 유도하기 위해 가격이 비공개임

**Comment by ainhye** [comment]
[ 포스팅 내용 기본 전제조건 ] 
1) 식사 사진 1주일 치 포함
2) 공간을 사용중인 사진을 포함하되 청소 직후와 의도된 사용감의 중간 정도로 연출)
3) 방 등급 별 가격 명시
4) 마사지 가격 오픈 가능하면 가장 좋음 (마사지 프로그램 어필 동반)

[ 컨텐츠 기획 예시 ]
ex1) 앙쥬클럽 조리원 교육팀장님이 20년간 조리원 교육을 진행해오며 자신있게 추천하는 조리원 시리즈
ex2) 마사지 가격을 공개할 수 있는 조리원 3곳의 마사지 프로그램, 가격, 제품 비교 (마사지를 중요시 하는 산모 고객 타겟)
ex3) 밥이 맛있기로 유명한 조리원 탐방
특별한 장점이 있는 조리원 탐방 (옥상정원, 유기농식단, 방마다 발코니, 그 외)
ex4) 원장님 또는 신생아 관리 선생님의 인터뷰가 가능한 곳 섭외 가능 시 인터뷰 내용 포함한 조리원 무물보 (무엇이든 물어보세요)

**Comment by singleview-co-kr** [comment]
20221024 앙쥬 컨텐츠 제작 기획 회의록에 의거하여
진행 보류함
