### ISSUE TITLE
카테고리 별 제품 리뷰 컨텐츠

### ISSUE THREAD

**Issue by singleview-co-kr** [mookhouse/xe-component#26]
20221024 앙쥬 컨텐츠 제작 기획 회의록에 의거하여 
2022년 말까지 1주에 1개씩 8개의 신규 컨텐츠 작성

**Comment by ainhye** [comment]
2022/10/25 영업팀 미팅 

1. 제품비교 컨텐츠
- 파트너사가 보기에 민감할 수 있는 부분 배제 요청
- 메인 제품군 70% (유모차 카시트 젖병 기저귀 외) + 서브제품이나 마땅한 가이드가 잘 없는 제품군 30% (기저귀 가방 등)
- 컨텐츠 팀과 업무영역 논의 필요 (컨텐츠 팀에서 제작만 할지, 디테일 사항 리서치 하여 내용도 작성할지) 

2. 언박싱
- 신제품 위주로 진행하나 신제품이 언제 나올지 불규칙 하기 때문에 파트너사에 문의하여 정보 취합(영업팀)
- 영상컨텐츠로 제작하는것이 좋겠다는 의견 (호스트가 중요..)
- 호스트 섭외 어려울 시 텍스트와 짧은 영상(짧)을 혼합한 글 형식으로 시작

**Comment by ainhye** [comment]
컨텐츠 기획 및 발행 일정 : 컨텐츠 팀 내부 캐파로 월 2건 제작 가능
https://docs.google.com/spreadsheets/d/1iRNtmbPPyWvL8rAs3iijQN3u-SWloI2kf7rUZ-wbYtY/edit#gid=199738656

1편 절충형 유모차 : https://ange.co.kr/usr/?menu=story404&submenu=story_detail&NO=9351
2편 디럭스 유모차 : https://ange.co.kr/usr/?menu=story404&submenu=story_detail&NO=9377
3편 물티슈 : 1월 20일
4편 올인원 아기띠 : 2월 초
