### ISSUE TITLE
신제품 언박싱 컨텐츠

### ISSUE THREAD

**Issue by singleview-co-kr** [mookhouse/xe-component#27]
20221024 앙쥬 컨텐츠 제작 기획 회의록에 의거하여
2022년 말까지 2주에 1개씩 4개의 신규 컨텐츠 작성

**Comment by ainhye** [comment]
**2022/10/25 영업팀 미팅** 

**2. 언박싱**
- 신제품 위주로 진행하나 신제품이 언제 나올지 불규칙 하기 때문에 파트너사에 문의하여 정보 취합(영업팀)
- 영상컨텐츠로 제작하는것이 좋겠다는 의견 (호스트가 중요..)
- 호스트 섭외 어려울 시 텍스트와 짧은 영상(짧)을 혼합한 글 형식으로 시작

**Comment by ainhye** [comment]
영업팀 협조 부재 + 영상 촬영 및 제작 캐파부족 하여 보류
