### ISSUE TITLE
이유식 가이드&레시피 컨텐츠

### ISSUE THREAD

**Issue by singleview-co-kr** [mookhouse/xe-component#28]
20221024 앙쥬 컨텐츠 제작 기획 회의록에 의거하여
2022년 말까지 보유 컨텐츠를 정리, 편집하여 신규 컨텐츠 작성

**Comment by ainhye** [comment]
- 컨텐츠 팀에서 2022년 11월 이유식 컨텐츠 부터 모바일 가독성을 고려한 레시피를 기존 웹사이트에 업로드.
- 기존에 1개 게시물에 레시피 6개가 올라가는 형태 > 11월 부터 게시물 1개 당 레시피 1개 업로드, 총 6개 게시글 업로드 예정
