### ISSUE TITLE
출산 맘박스 인지도 개선

### ISSUE THREAD

**Issue by singleview-co-kr** [mookhouse/xe-component#31]
- [x] "앙쥬맘박스" 네이버 브랜드 검색 키워드 추가
- [x] 국민행복카드를 앙쥬에서 신청 대행할 수 없는 이유 조사
- [x] 네이버 맘박스 관련 CPC 키워드 등록
- [x] GA 맘박스 신청하기 클릭 전환 목표 설정
- [x] 네이버 비즈머니 50만원 충전
- [x] 네이버 맘박스 관련 CPC 키워드 1위 입찰
- [x] 네이버 맘박스 관련 CPC 키워드 유입 결과 확인
- [x] 메인 페이지의 브랜드뉴스 섹션을 단순 이미지 배너료 교체하고 출산맘박스 배너로 교체

**Comment by singleview-co-kr** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/w9721066/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/w9721066/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link=blue vlink=purple>



연관키워드 | 월간검색수(PC) | 월간검색수(모바일) | 월평균클릭수(PC) | 월평균클릭수(모바일) | 월평균클릭률(PC) | 월평균클릭률(모바일) | 경쟁정도 | 월평균노출 광고수
-- | -- | -- | -- | -- | -- | -- | -- | --
맘박스 | 30 | 140 | 1.6 | 15.5 | 5.29% | 11.08% | 중간 | 9
무료임신축하선물 | 230 | 1,240 | 10.9 | 115.9 | 4.79% | 10.17% | 높음 | 15
맘스팩 | 60 | 280 | 10 | 83 | 22.73% | 34.3% | 낮음 | 2
임신박스 | 220 | 1,160 | 10.6 | 119.8 | 5.13% | 11.03% | 높음 | 15
임신축하박스 | 580 | 3,660 | 24.1 | 385.2 | 4.4% | 11.19% | 높음 | 15
위드앤육아 | 80 | 370 | 7.3 | 52.3 | 8.95% | 15.17% | 낮음 | 3
국민행복카드 | 11,400 | 49,900 | 75 | 1068.4 | 0.7% | 2.28% | 높음 | 15
임신축하선물 | 1,520 | 7,940 | 4.5 | 114.5 | 0.32% | 1.54% | 높음 | 15
임산부무료선물 | 20 | 200 | 0.3 | 17.8 | 1.31% | 9.86% | 높음 | 15
임신무료선물 | 30 | 280 | 0.9 | 40.8 | 3.23% | 15.33% | 높음 | 15
부산산모교실 | 50 | 420 | 0.8 | 5.8 | 1.68% | 1.49% | 중간 | 13
임산부이벤트 | 80 | 290 | 3.1 | 27.5 | 3.57% | 10.08% | 높음 | 15
임산부박스 | 30 | 200 | 1.4 | 11.3 | 4.25% | 5.72% | 중간 | 12
출산박스 | 40 | 370 | 2.9 | 27 | 5.99% | 7.65% | 높음 | 15
미즈톡톡 | 4,050 | 18,200 | 408 | 3319 | 10.71% | 19.32% | 낮음 | 1
임산부무료 | 40 | 170 | 1.3 | 15.8 | 3.97% | 9.91% | 중간 | 9
임산부혜택 | 1,060 | 3,250 | 2.9 | 23.4 | 0.29% | 0.77% | 높음 | 15
임신선물박스 | 80 | 550 | 1.3 | 39 | 1.57% | 7.56% | 높음 | 15
임산부샘플 | 10 | 130 | 0.6 | 5 | 4% | 4.04% | 중간 | 8
국민행복카드사은품 | 700 | 3,490 | 65.9 | 334.3 | 10.17% | 10.3% | 중간 | 6
무료출산선물 | 10 | 80 | 0.1 | 11 | 1.5% | 13.42% | 높음 | 15
무료임신선물 | 10 | 90 | 0.1 | 0.7 | 0.55% | 0.89% | 높음 | 14
무료임신축하박스 | 10 | 40 | 0.9 | 3.3 | 6.67% | 7.23% | 중간 | 12
임산부지원 | 370 | 1,310 | 2 | 20.4 | 0.59% | 1.68% | 중간 | 13
무료임신박스 | 10 | 80 | 1.7 | 9.5 | 9.55% | 11.18% | 중간 | 13



</body>

</html>

**Comment by ainhye** [comment]
*국민행복카드를 앙쥬에서 신청 대행할 수 없는 이유 조사 :

국민행복카드는 앙쥬도 카드사에서 홍보 해달라고 의뢰가 오면 홍보대행 할 수 있으나 
카드사가 앙쥬를 광고 회사로 인식하지 않고 있어서 의뢰가 들어오지 않고 있고
컨텍포인트를 몰라서 영업 쪽에서 먼저 컨텍하는 것도 어려운 상황.

**Comment by ainhye** [comment]
1) 메인페이지 오른쪽 서브베너에 출산맘박스 배너 개시 (42만원 상당의 무료선물 강조)
2) 네이버 브검 PC : 작은 썸네일에 출산맘박스 소재 추가
3) 네이버 브검 MO : 작은 썸네일과 새소식에 출산맘박스 소재 추가
