### ISSUE TITLE
네이버 매체 대행사 지정

### ISSUE THREAD

**Issue by singleview-co-kr** [mookhouse/xe-component#5]

**Comment by ainhye** [comment]
네이버 매체 대행사 지정 : 스노우맨
담당자 : 지재우 님 <jjw@snowmanad.co.kr>

1) 세금계산서 발행 : 스노우맨에 위임발행
2) 세금계산서 발행처 변경(이관)을 위해 앙쥬의 네이버 광고계정 및 비밀번호 공유완료
3) 네이버 검색광고 담당자 및 세금계산서 발행처 변경완료 : 주식회사 트리니티
 * 원대행사_디지털트리니티/ 재대행_스노우맨 : 앙쥬는 스노우맨으로부터 세금계산서를 수령예정
4) 위임발행시 세금계산서는 광고비 소진금액에 한하여 발행되기 때문에 
   현재 계정에 남아있는 충전금 약 30만원은 대행사 지정과정에 문제 되지 않음 확인
