### ISSUE TITLE
최소 30개의 중요 포스팅 변경없이 등록

### ISSUE THREAD

**Issue by singleview-co-kr** [mookhouse/xe-component#8]

**Comment by singleview-co-kr** [comment]
기존 홈피에서 단순 복붙으로는 포스팅 이미지가 표시되지 않을 수 있음
컨텐트 서버에서는 확장자가 명시되지 않은 이미지 파일을 로드하지 않기 때문

**Comment by ainhye** [comment]
1) 본문 복사 붙여넣기
2) 썸네일 다른이름으로 저장 > 저장 후 확장자 JPG로 변경 > 변경 후 파일명 컨텐츠 관련 검색어로 변경
3) 업로드한 컨텐츠 수정 > 썸네일 이미지 첨부 > 본문에서 출력된 이미지 삭제 > 저장

*가로로 길어서 썸네일로 적합하지 않은 이미지 일부는 적합한 이미지로 대체함
